#!/bin/bash

# Get the right workspace ID
sed -i -e "s|/lab|/user/${JUPYTERHUB_USER}/lab|g" binder/workspace.json

# Import the workspace into JupyterLab
jupyter lab workspaces import binder/workspace.json \
  --NotebookApp.base_url=user/${JUPYTERHUB_USER}

exec "$@"
